---
title: "rare_data"
output:
#  pdf_document:
#    toc: yes
  html_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Introduction
========================================================
General descriptuve statistics for 2015 rare data collected by Ohio State.

Distribution
========================================================
The git repo holding this code is available at:
https://github.com/puruckertom/rare_pollen

Computational environment
========================================================

```{r eval=FALSE, echo=FALSE}
#library(installr) #windows only currently
#updateR()
```
Version and installed libraries.
```{r eval=TRUE, echo=TRUE}
verbose_output = TRUE

if(verbose_output){
  print(Sys.info()[4])
  R.Version()$version.string
}
#check to see if needed packages are installed
list.of.packages <- c("ggplot2", "dplyr")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
#load relevant packages
library(MASS)
library(dplyr, warn.conflicts = FALSE)
library(ggplot2)
library(reshape2)

if(verbose_output){
  print("list of loaded packages: ")
  print((.packages()))
}
```

```{r eval=TRUE, echo=FALSE}
if(Sys.info()[4]=="DZ2626UTPURUCKE"){
  rare_data <- "k:\\git\\rare_pollen\\"
}

if(Sys.info()[4]=="stp-air.local" || Sys.info()[4]=="stp-air"){
  rare_data <- path.expand("~/git/rare_pollen/")
}

osu_data <- paste(rare_data, "data_in/", sep="")
```

Observational data
========================================================
Original file with observational data: 
https://github.com/puruckertom/rare_pollen/blob/master/data_in/rare_data_osu_2015.csv

```{r eval=TRUE, echo=TRUE}
##################
#the data sets
##################
#import raw data - everything
file.exists(paste(osu_data,"rare_data_osu_2015.csv",sep=""))
osu_obs <- read.table(paste(osu_data,"rare_data_osu_2015.csv",sep=""), header = TRUE, sep = ",")
str(osu_obs)

#melt to long format
keepers <- colnames(osu_obs)[1:9]
osu_concs <- melt(osu_obs, id.vars = keepers, variable.name = "neonic", value.name = "conc")
dim(osu_concs)
colnames(osu_concs)

#add detected field and numerical concentration
osu_concs$conc
osu_concs$detected <- ifelse(grepl("<", osu_concs$conc),0,1)
osu_concs$conc2 <- as.numeric(gsub("< ", "", osu_concs$conc))
View(osu_concs)

```

Summary statistics
```{r eval=TRUE, echo=TRUE}
str(osu_concs)

#aggregate(osu_concs$conc2, list(osu_concs$neonic), mean)
```
